/**
 * @file ChatLog.js
 * @description Mongoose model representing a Chat Log for analytics and monitoring.
 * Logs every user message, AI response, execution latency (responseTimeMs), token usage metrics, 
 * user ratings, and error tracking.
 * Implements a 90-day Time-To-Live (TTL) index to keep database storage lean.
 */

import mongoose from 'mongoose'

/**
 * @typedef {Object} TokenUsage
 * @property {number} [promptTokens] Number of tokens in the prompt query sent to the LLM.
 * @property {number} [completionTokens] Number of tokens in the generated response.
 * @property {number} [totalTokens] Sum of prompt and completion tokens.
 */

/**
 * @typedef {Object} ChatLog
 * @property {string} collegeId Foreign key referencing the College's collegeId. Part of tenant isolation.
 * @property {string} userId User identifier, usually the sender's E.164 phone number.
 * @property {string} [studentId] Unique student roll number if the sender is an activated student.
 * @property {string} userQuery The text query or message sent by the user.
 * @property {string} [aiResponse] The text response generated by the AI assistant.
 * @property {number} [responseTimeMs] The latency in milliseconds for generating and sending the response.
 * @property {TokenUsage} [tokensUsed] Structural break down of LLM token usage.
 * @property {number} [rating] User-provided quality rating for the AI response (e.g., 1 to 5 stars).
 * @property {string} [model] The identifier of the AI model used (e.g., "gemini-2.0-flash").
 * @property {boolean} hadRagContext Whether document context was retrieved and injected via RAG.
 * @property {boolean} isActivation Whether this chat exchange was part of the student activation flow.
 * @property {string} [error] Error message stack if message processing or LLM generation failed.
 * @property {Date} timestamp The date and time when the chat activity took place.
 */

const ChatLogSchema = new mongoose.Schema({
  // ─── Tenant Isolation ───────────────────────────────────────────────────
  /**
   * Foreign key referencing the College's collegeId.
   * Isolates records to a specific tenant.
   * @type {String}
   */
  collegeId: {
    type: String,
    required: true,
    trim: true,
    index: true
  },

  // ─── Identity ───────────────────────────────────────────────────────────
  /**
   * Phone number of the student/user in E.164 format.
   * @type {String}
   */
  userId: {
    type: String,
    required: true,
    trim: true
  },

  /**
   * Roll number of the student (Student.studentId) if they are activated.
   * @type {String}
   */
  studentId: {
    type: String,
    trim: true
  },

  // ─── Content ────────────────────────────────────────────────────────────
  /**
   * User query/input message. Truncated to 1000 characters if excessively long.
   * @type {String}
   */
  userQuery: {
    type: String,
    required: true,
    trim: true
  },

  /**
   * AI generated response sent back to the student.
   * @type {String}
   */
  aiResponse: {
    type: String,
    trim: true
  },

  // ─── Performance Metrics ────────────────────────────────────────────────
  /**
   * Time taken in milliseconds from receiving the message to completing the WhatsApp reply.
   * @type {Number}
   */
  responseTimeMs: {
    type: Number,
    min: 0
  },

  /**
   * Token usage detailed count.
   */
  tokensUsed: {
    promptTokens: { type: Number, default: 0 },
    completionTokens: { type: Number, default: 0 },
    totalTokens: { type: Number, default: 0 }
  },

  // ─── Quality & Analytics ────────────────────────────────────────────────
  /**
   * User-submitted rating for the answer quality (e.g. 1-5 scale).
   * Used to monitor bot performance and identify weak context patterns.
   * @type {Number}
   */
  rating: {
    type: Number,
    min: 1,
    max: 5
  },

  /**
   * Large Language Model name in use during message generation.
   * @type {String}
   */
  model: {
    type: String,
    trim: true
  },

  /**
   * Flag indicating whether RAG context was successfully retrieved and used.
   * @type {Boolean}
   */
  hadRagContext: {
    type: Boolean,
    default: false
  },

  /**
   * Flag indicating if the exchange was a student self-registration attempt.
   * @type {Boolean}
   */
  isActivation: {
    type: Boolean,
    default: false
  },

  /**
   * Full descriptive error log if message processing or network delivery failed.
   * @type {String}
   */
  error: {
    type: String,
    trim: true
  },

  // ─── Timestamp ──────────────────────────────────────────────────────────
  /**
   * The datetime when the interaction took place.
   * @type {Date}
   */
  timestamp: {
    type: Date,
    required: true,
    default: Date.now,
    index: true
  }

}, {
  timestamps: true
})

// ─── TTL (Time-To-Live) Index ─────────────────────────────────────────────
/**
 * Auto-deletes logs older than 90 days. Keep storage footprint predictable.
 * 90 Days in Seconds = 90 * 24 * 60 * 60 = 7,776,000 seconds.
 */
ChatLogSchema.index({ timestamp: 1 }, { expireAfterSeconds: 7_776_000 })

// ─── Query Indexes ────────────────────────────────────────────────────────
/**
 * Compound index on { collegeId, timestamp }.
 * Speeds up dashboard analytics loading charts like message counts or latencies over time.
 */
ChatLogSchema.index({ collegeId: 1, timestamp: -1 })

/**
 * Compound index on { collegeId, studentId, timestamp }.
 * Speeds up historical chat inspection for a specific student.
 */
ChatLogSchema.index({ collegeId: 1, studentId: 1, timestamp: -1 })

export const ChatLog = mongoose.model('ChatLog', ChatLogSchema)
export default ChatLog
